### ISSUE TITLE
Newspaper3k

### ISSUE THREAD

**Issue by Immortalin** [wybiral/stream-sources#2]
Will make life easier

**Comment by wybiral** [comment]
Thanks for the recommendation. That modules looks like it could be really useful.

This project is more focused on collecting: link, title, and summary; but it would be interesting to experiment with using something like newspaper3k to extract more of the article.

**Comment by Immortalin** [comment]
Do you plan to have a config for update frequency? Or maybe something like `urlwatch`? I think both would be nice i.e. for infrequently updated sites like a blog it can be routine scraping and change detection while for breaking news it's near real-time.

**Comment by wybiral** [comment]
I'm opening the update frequency as issue #5 and closing this one. Thanks!
